columns:
  age : int
  sex : category
  on thyroxine : category 
  query on thyroxine : category
  on antithyroid medication : category
  sick : category
  pregnant : category
  thyroid surgery : category
  I131 treatment : category
  query hypothyroid : category
  query hyperthyroid : category
  lithium : category
  goitre : category
  tumor : category
  hypopituitary :  category
  psych : category
  TSH : float
  T3 :  float
  TT4 : float
  T4U : float
  FTI : float 
  referral source : category
  binaryClass : category


numerical_columns:
  - TSH 
  - T3 
  - TT4 
  - T4U 
  - FTI 
  


categorical_columns:
  - age 
  - sex 
  - on thyroxine 
  - query on thyroxine 
  - on antithyroid medication 
  - sick 
  - pregnant 
  - thyroid surgery 
  - I131 treatment
  - query hypothyroid 
  - query hyperthyroid 
  - lithium 
  - goitre 
  - tumor 
  - hypopituitary 
  - psych 





  



